version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./keycloak_data:/var/lib/postgresql/data/
    env_file:
      - .env

  keycloak:
    image: jboss/keycloak:latest
    restart: always
    env_file:
      - .env.sample
    ports:
      - '${PORT}:8080'
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
